name: LumaPvPLobby
main: it.lumapvp.lobby.LumaPvPLobby
version: 1.0.0
api-version: 1.8
description: Plugin Lobby ufficiale di LumaPvP
author: Ck_Ant0

commands:
  lumapvpadmin:
    description: Comandi admin LumaPvP
    usage: /lumapvpadmin <setlobby|setparkour|build|reload>
    permission: lumapvp.admin
  lumapvplobby:
    description: Comandi lobby LumaPvP
    usage: /lumapvplobby <reload>
    permission: lumapvp.admin
  vanish:
  gmc:
    description: Imposta Gamemode Creativa
    usage: /gmc [player]
    permission: lumapvp.staff
  gms:
    description: Imposta Gamemode Survival
    usage: /gms [player]
    permission: lumapvp.staff
  gmsp:
    description: Imposta Gamemode Spectator
    usage: /gmsp [player]
    permission: lumapvp.staff
  flyspeed:
    description: Set fly speed
    usage: /flyspeed <1-10> [player]
    permission: lumapvp.staff
  fly:
    description: Toggle flight
    usage: /fly [player]
    permission: lumapvp.staff

permissions:
  lumapvp.admin:
    description: Permessi da admin LumaPvP
    default: op
  lumapvp.staff:
    description: Permessi da staff LumaPvP
    default: op
  lumapvp.rank.vip:
    description: Rank VIP
    default: false
  lumapvp.rank.mvp:
    description: Rank MVP
    default: false
  lumapvp.rank.staff:
    description: Rank Staff
    default: false
  lumapvp.rank.admin:
    description: Rank Admin
    default: false
